version: '3.3'
services:
    shlink:
        container_name: my_shlink
        ports:
            - '8080:8080'
        environment:
            - DEFAULT_DOMAIN=s.test
            - IS_HTTPS_ENABLED=false
            - GEOLITE_LICENSE_KEY=
        image: 'shlinkio/shlink:stable'
