version: '3.3'
services:
    guacamole:
        ports:
            - '8090:8080'
        volumes:
           - '/opt/guacamole/config:/config'
        environment:
            - 'EXTENSIONS=auth-totp'
        image: maxwaldorf/guacamole
