version: '3'
services:
  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    privileged: true
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9000:9000'
    container_name: portainer
    networks:
      - nginxproxymanager_default
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  nginxproxymanager_default:
    external: true
