version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes: 
      - /opt/mongodata:/data/db
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - '5432:5432'
    volumes: 
      - ./src/seeder/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /opt/postgresdata:/var/lib/postgresql/data

